name: Resonance
options:
  bundleIdPrefix: com.y4sh.resonance
  deploymentTarget:
    iOS: "26.0"
    watchOS: "26.0"
    macOS: "26.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true
  groupSortPosition: top

settings:
  base:
    DEVELOPMENT_TEAM: "69YKR4K9LC"
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.9"
    ENABLE_BITCODE: false
    CODE_SIGN_STYLE: Automatic

# Shared file groups
fileGroups:
  - Shared
  - Brain

targets:
  # ============================================
  # iOS App Target
  # ============================================
  Resonance:
    type: application
    platform: iOS
    deploymentTarget: "26.0"
    sources:
      - path: iOS
        excludes:
          - "**/*.entitlements"
      - path: Shared
      - path: Brain
    entitlements:
      path: iOS/Entitlements/Resonance.entitlements
    info:
      path: iOS/Info.plist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.y4sh.resonance.ios
        INFOPLIST_FILE: iOS/Info.plist
        CODE_SIGN_ENTITLEMENTS: iOS/Entitlements/Resonance.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks"
        TARGETED_DEVICE_FAMILY: "1,2"  # iPhone and iPad
    dependencies:
      - target: ResonanceWidgets
        embed: true
      - target: ResonanceWatch
        embed: false  # Watch apps are handled differently
    preBuildScripts: []
    postBuildScripts: []

  # ============================================
  # watchOS App Target
  # ============================================
  ResonanceWatch:
    type: application
    platform: watchOS
    deploymentTarget: "26.0"
    sources:
      - path: Watch
        excludes:
          - "**/*.entitlements"
      - path: Shared/Models
      - path: Shared/Utilities
    entitlements:
      path: Watch/Entitlements/ResonanceWatch.entitlements
    info:
      path: Watch/Info.plist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.y4sh.resonance.watchkitapp
        INFOPLIST_FILE: Watch/Info.plist
        CODE_SIGN_ENTITLEMENTS: Watch/Entitlements/ResonanceWatch.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        SKIP_INSTALL: false
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks"

  # ============================================
  # macOS Menu Bar App Target
  # ============================================
  ResonanceMac:
    type: application
    platform: macOS
    deploymentTarget: "26.0"
    sources:
      - path: macOS
        excludes:
          - "**/*.entitlements"
      - path: Shared/Models
      - path: Shared/Utilities
    entitlements:
      path: macOS/Entitlements/ResonanceMac.entitlements
    info:
      path: macOS/Info.plist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.y4sh.resonance.macos
        INFOPLIST_FILE: macOS/Info.plist
        CODE_SIGN_ENTITLEMENTS: macOS/Entitlements/ResonanceMac.entitlements
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/../Frameworks"
        COMBINE_HIDPI_IMAGES: true

  # ============================================
  # iOS Widget Extension Target
  # ============================================
  ResonanceWidgets:
    type: extensionkit-extension
    platform: iOS
    deploymentTarget: "26.0"
    sources:
      - path: Widgets
        excludes:
          - "**/*.entitlements"
      - path: Shared/Models
      - path: Shared/Utilities/Constants.swift
    entitlements:
      path: Widgets/ResonanceWidgets.entitlements
    info:
      path: Widgets/Info.plist
      properties:
        EXAppExtensionAttributes:
          EXExtensionPointIdentifier: com.apple.widgetkit-extension
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.y4sh.resonance.ios.widgets
        INFOPLIST_FILE: Widgets/Info.plist
        CODE_SIGN_ENTITLEMENTS: Widgets/ResonanceWidgets.entitlements
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks @executable_path/../../Frameworks"
        SKIP_INSTALL: true

  # ============================================
  # Unit Tests Target
  # ============================================
  ResonanceTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "26.0"
    sources:
      - path: Tests
    dependencies:
      - target: Resonance
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.y4sh.resonance.tests
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/Resonance.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/Resonance"
        BUNDLE_LOADER: "$(TEST_HOST)"

schemes:
  # ============================================
  # iOS App Scheme
  # ============================================
  Resonance:
    build:
      targets:
        Resonance: all
        ResonanceWidgets: all
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - ResonanceTests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release

  # ============================================
  # Watch App Scheme
  # ============================================
  ResonanceWatch:
    build:
      targets:
        ResonanceWatch: all
    run:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release

  # ============================================
  # macOS App Scheme
  # ============================================
  ResonanceMac:
    build:
      targets:
        ResonanceMac: all
    run:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release

  # ============================================
  # All Targets Scheme
  # ============================================
  AllTargets:
    build:
      targets:
        Resonance: all
        ResonanceWatch: all
        ResonanceMac: all
        ResonanceWidgets: all
        ResonanceTests: ["test"]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - ResonanceTests
