name: AIDJ
options:
  bundleIdPrefix: com.aidj
  deploymentTarget:
    iOS: "15.0"
    watchOS: "8.0"
    macOS: "12.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true
  groupSortPosition: top

settings:
  base:
    DEVELOPMENT_TEAM: ""  # Set your team ID here
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.9"
    ENABLE_BITCODE: false
    CODE_SIGN_STYLE: Automatic

# Shared file groups
fileGroups:
  - Shared
  - Brain

targets:
  # ============================================
  # iOS App Target
  # ============================================
  AIDJ:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: iOS
        excludes:
          - "**/*.entitlements"
      - path: Shared
      - path: Brain
    entitlements:
      path: iOS/Entitlements/AIDJ.entitlements
    info:
      path: iOS/Info.plist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.aidj.ios
        INFOPLIST_FILE: iOS/Info.plist
        CODE_SIGN_ENTITLEMENTS: iOS/Entitlements/AIDJ.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks"
        TARGETED_DEVICE_FAMILY: "1,2"  # iPhone and iPad
    dependencies:
      - target: AIDJWidgets
        embed: true
      - target: AIDJWatch
        embed: false  # Watch apps are handled differently
    preBuildScripts: []
    postBuildScripts: []

  # ============================================
  # watchOS App Target
  # ============================================
  AIDJWatch:
    type: application
    platform: watchOS
    deploymentTarget: "8.0"
    sources:
      - path: Watch
        excludes:
          - "**/*.entitlements"
      - path: Shared/Models
      - path: Shared/Utilities
    entitlements:
      path: Watch/Entitlements/AIDJWatch.entitlements
    info:
      path: Watch/Info.plist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.aidj.watchkitapp
        INFOPLIST_FILE: Watch/Info.plist
        CODE_SIGN_ENTITLEMENTS: Watch/Entitlements/AIDJWatch.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        SKIP_INSTALL: false
        WATCHOS_DEPLOYMENT_TARGET: "8.0"
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks"

  # ============================================
  # macOS Menu Bar App Target
  # ============================================
  AIDJMac:
    type: application
    platform: macOS
    deploymentTarget: "12.0"
    sources:
      - path: macOS
        excludes:
          - "**/*.entitlements"
      - path: Shared/Models
      - path: Shared/Utilities
    entitlements:
      path: macOS/Entitlements/AIDJMac.entitlements
    info:
      path: macOS/Info.plist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.aidj.macos
        INFOPLIST_FILE: macOS/Info.plist
        CODE_SIGN_ENTITLEMENTS: macOS/Entitlements/AIDJMac.entitlements
        MACOSX_DEPLOYMENT_TARGET: "12.0"
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/../Frameworks"
        COMBINE_HIDPI_IMAGES: true

  # ============================================
  # iOS Widget Extension Target
  # ============================================
  AIDJWidgets:
    type: app-extension
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: Widgets
        excludes:
          - "**/*.entitlements"
      - path: Shared/Models
      - path: Shared/Utilities/Constants.swift
    entitlements:
      path: Widgets/AIDJWidgets.entitlements
    info:
      path: Widgets/Info.plist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.aidj.ios.widgets
        INFOPLIST_FILE: Widgets/Info.plist
        CODE_SIGN_ENTITLEMENTS: Widgets/AIDJWidgets.entitlements
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks @executable_path/../../Frameworks"
        SKIP_INSTALL: true

  # ============================================
  # Unit Tests Target
  # ============================================
  AIDJTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: Tests
    dependencies:
      - target: AIDJ
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.aidj.tests
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/AIDJ.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/AIDJ"
        BUNDLE_LOADER: "$(TEST_HOST)"

schemes:
  # ============================================
  # iOS App Scheme
  # ============================================
  AIDJ:
    build:
      targets:
        AIDJ: all
        AIDJWidgets: all
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - AIDJTests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release

  # ============================================
  # Watch App Scheme
  # ============================================
  AIDJWatch:
    build:
      targets:
        AIDJWatch: all
    run:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release

  # ============================================
  # macOS App Scheme
  # ============================================
  AIDJMac:
    build:
      targets:
        AIDJMac: all
    run:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release

  # ============================================
  # All Targets Scheme
  # ============================================
  AllTargets:
    build:
      targets:
        AIDJ: all
        AIDJWatch: all
        AIDJMac: all
        AIDJWidgets: all
        AIDJTests: ["test"]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - AIDJTests
