#!/usr/bin/swift
//
//  train_feature_models.swift
//  Resonance
//
//  Create ML training script for AudioFeatureRegressor models.
//  Trains 4 boosted tree regressors (bpm, energy, valence, instrumentalness)
//  from a CSV generated by generate_training_data.py.
//
//  Usage:
//      swift train_feature_models.swift [path/to/training_data.csv]
//
//  Requirements:
//      - macOS 13+ with Xcode / Command Line Tools
//      - Create ML framework
//

import CreateML
import Foundation
import TabularData

// MARK: - Configuration

let inputFile: String
if CommandLine.arguments.count > 1 {
    inputFile = CommandLine.arguments[1]
} else {
    inputFile = "training_data.csv"
}

let outputDirectory = "Models"
let targets = ["bpm", "energy", "valence", "instrumentalness"]
let maxIterations = 100
let maxDepth = 6

// MARK: - Load Data

print("Loading training data from: \(inputFile)")

let fileURL = URL(fileURLWithPath: inputFile)
guard FileManager.default.fileExists(atPath: inputFile) else {
    print("Error: File not found at \(inputFile)")
    print("Run generate_training_data.py first to create the CSV.")
    exit(1)
}

let dataFrame: DataFrame
do {
    dataFrame = try DataFrame(contentsOfCSVFile: fileURL)
} catch {
    print("Error loading CSV: \(error.localizedDescription)")
    exit(1)
}

print("Loaded \(dataFrame.rows.count) rows, \(dataFrame.columns.count) columns")
print("Columns: \(dataFrame.columns.map { $0.name }.joined(separator: ", "))")

// MARK: - Split Data

let (trainingData, testingData) = dataFrame.randomSplit(by: 0.8)
print("Training set: \(trainingData.rows.count) rows")
print("Testing set:  \(testingData.rows.count) rows")
print()

// MARK: - Create Output Directory

let outputURL = URL(fileURLWithPath: outputDirectory)
try? FileManager.default.createDirectory(at: outputURL, withIntermediateDirectories: true)

// MARK: - Feature Columns

let featureColumns = ["genre", "duration", "year", "genreCount", "trackNumber", "isExplicit"]

// MARK: - Train Models

for target in targets {
    print("--- Training model for: \(target) ---")

    do {
        let parameters = MLBoostedTreeRegressor.ModelParameters(
            validation: .split(strategy: .automatic),
            maxIterations: maxIterations,
            maxDepth: maxDepth
        )

        let model = try MLBoostedTreeRegressor(
            trainingData: DataFrame(trainingData),
            targetColumn: target,
            featureColumns: featureColumns,
            parameters: parameters
        )

        // Evaluate on test set
        let evaluation = model.evaluation(on: DataFrame(testingData))
        let rmse = evaluation.rootMeanSquaredError
        let mae = evaluation.maximumError

        print("  RMSE: \(String(format: "%.4f", rmse))")
        print("  Max Error: \(String(format: "%.4f", mae))")

        // Save model
        let modelURL = outputURL.appendingPathComponent("\(target)_regressor.mlmodel")
        try model.write(to: modelURL)
        print("  Saved: \(modelURL.lastPathComponent)")
        print()

    } catch {
        print("  Error training \(target) model: \(error.localizedDescription)")
        print()
    }
}

print("Training complete. Models saved to \(outputDirectory)/")
print()
print("Next steps:")
print("  1. Open each .mlmodel in Xcode to compile to .mlmodelc")
print("  2. Or use: xcrun coremlcompiler compile <model>.mlmodel <output_dir>")
print("  3. Add compiled models to the Resonance app bundle")
